### ISSUE TITLE
 1.14.4-0.1a crashes dedicated server Forge 1.14.4 build 28.1.70

### ISSUE THREAD

**Issue by kreezxil** [vincentmet/CustomQuests#1]
Notes:
     looking for client side classes on a dedicated server

crash report:
http://paste.ubuntu.com/p/R8xRq82btX/

fml server latest:
http://paste.ubuntu.com/p/ZRgshBfNXz/

**Comment by vincentmet** [comment]
As mentioned in the 0.1 changelog, its not yet server compatible, altough i am working on it rn to fix it

**Comment by kreezxil** [comment]
ok send me a message when you got it server ready. I could really use it
for World of Dragons - A New Age

**Comment by vincentmetevelis** [comment]
About a week ago, I released a new version that fixes the server compat issue

**Comment by vincentmet** [comment]
About a week ago, I released a new version that fixes the server compat issue

**Comment by kreezxil** [comment]
thank you, I'll take a look at it again.
