### ISSUE TITLE
Jsons in sub-directory

### ISSUE THREAD

**Issue by MelanX** [vincentmet/CustomQuests#11]
I think it would be good to add your ```Quests.json``` and ```QuestBook.json``` to a sub-directory. Why? If the user has multiple questing mods installed and at least 2 of them are genius enough to generate the same json file, it will be overriden and errors could occur.

**Comment by vincentmetevelis** [comment]
Since it'll break current servers/worlds, i wont do it. And, why would someone have 2 questing mods installed?
