### ISSUE TITLE
Menu GUI is broken

### ISSUE THREAD

**Issue by PyroFlareX** [vincentmet/CustomQuests#15]
The sections in the default quests in the menu are permanently locked to the last one, regardless of what you click. The quests change in the menu, but the current section is not indicated in the GUI.

**Comment by vincentmetevelis** [comment]
What do you mean by "section"?

**Comment by vincentmetevelis** [comment]
Do you mean the example quests?, in that case, because there are no quests in the questline, the button is greyed out.
