### ISSUE TITLE
QuestRequirement.java BLOCK_MINE wrong type

### ISSUE THREAD

**Issue by Amoo0001** [vincentmet/CustomQuests#16]
[This line:](https://github.com/vincentmetevelis/CustomQuests/blob/a3d6ea28b7ae4e00fcfeb18f08c2cbb2085ea0a9/src/main/java/com/vincentmet/customquests/quests/QuestRequirement.java#L45)
```java
            case BLOCK_MINE:
                json.addProperty("type", "ITEM_DELIVER");
                break;
```
should probably be:
```java
            case BLOCK_MINE:
                json.addProperty("type", "BLOCK_MINE");
                break;
```

**Comment by vincentmetevelis** [comment]
I did so on purpose until i implement the type to prevent a crash when launching the game with this type
