### ISSUE TITLE
[REQUEST] Spawn Entity Reward with Custom NBT

### ISSUE THREAD

**Issue by Amoo0001** [vincentmet/CustomQuests#17]
I'm trying to spawn a villager with custom trades as a reward for completing a quest.  I tried with a COMMAND reward but I couldn't figure out where it was putting it when I did `~ ~1 ~`, and the SPAWN_ENTITY reward doesn't currently support custom NBT.

If it's alright, I would really like to be able to spawn entities with custom NBT :)

**Comment by vincentmetevelis** [comment]
Currently doing a rewrite of the mod, and will take this into account
