### ISSUE TITLE
Quest Item Rwards cannot have NBT

### ISSUE THREAD

**Issue by hotdog95** [vincentmet/CustomQuests#20]
Mod Version 1.0.8
Forge Version 28.2.11

Item rewards NBT tag is reset in the Quests.json file on quest load always defaulting to an empty NBT string, both command and game reload do this, tested with reward:

`{
  "type": "ITEMS",
  "content": {
    "item": "minecraft:leather_boots",
    "amount": 1,
    "nbt": "{Enchantments:[{id:\"minecraft:unbreaking\",lvl:3}]}"
  }
}`

**Comment by hotdog95** [comment]
As a side note, add a way to target the player who achieved the quest for commands so commands like /enchant or /give can work (while these examples would be find with working NBT tags, I was trying solutions to my problem, it would be handy to have a target, say give the player flight through commands)

**Comment by vincentmetevelis** [comment]
That should be working by using @p in the command. since im internally fireing the command with the "/execute" command at the players location

**Comment by hotdog95** [comment]
Ah awesome, I was looking into it and I saw that minecraft data packs execute it world origin, so I assumed that's what your mod was doing too, glad to know I was wrong, in the mean time I think I can just use the give command for the nbt specific items (enchanted items and silents treasure bags) I want them to get, just until this issue is fixed.

**Comment by vincentmetevelis** [comment]
As far as i know, the nbt /should/ work for the item rewards 🤔

**Comment by hotdog95** [comment]
Well if it helps, I have noticed that it seems to be getting the items default nbt and saving as that, from testing with Silents Treasure Bags, I have noticed that NBT has been set to the bag's default NBT data and not blank.

**Comment by vincentmetevelis** [comment]
Ill check it out later

**Comment by vincentmetevelis** [comment]
In the rewrite(not out yet, this has been solved (by storing it in a separate variable and using the variable to write again))
