### ISSUE TITLE
Unclaimed quests are reawarded to the player preventing quest reloading

### ISSUE THREAD

**Issue by hotdog95** [vincentmet/CustomQuests#21]
Version: 1.0.8

Any unclaimed quest is reawarded to the player, this sets Ref.saveOnNextTick to true, preventing any adjustment to the quests, the ingame title overlay does not reappear, and this only happens when the quest items are in the inventory.

**Comment by vincentmetevelis** [comment]
Ill see what i can do

**Comment by vincentmetevelis** [comment]
Idk why i used a bool flag for saving like that anyway on the client... This should be fixed in the rewrite anyway (tested it as far as i could by myself)
