### ISSUE TITLE
Freeze while accessing questline page

### ISSUE THREAD

**Issue by Fungidelight** [vincentmet/CustomQuests#25]
Hi, I am not sure what is causing this since there is no crash log when game freezes. I am currently testing a mod pack with ~530 quests, and about 10-15 minutes into play the game freezes when you attempt to use the questing device. Force-quitting and restarting resets this apparent timer, until the next freeze - hence I am suspecting a memory leak. A few minutes before the game freezes completely I notice slight lag when opening the quest book.

I have re-designed the questlines in such a way that no more than about 30 quests can be open at one time, so the number of active quests is not an issue here.

Using version customquests-1.15.2-1.0.1.jar

Version of modpack is 1.9.0, if you wish to test it:
https://www.curseforge.com/minecraft/modpacks/natural-history-museum

**Comment by Fungidelight** [comment]
Update: Found a workaround to the freeze, it does not happen if when leaving the quest book the player is within a quest rather than on the questline page. But it would still be nice to find the cause of questline page freezes and get rid of it if possible.

**Comment by vincentmetevelis** [comment]
Since this is the old version, ill probably not fix this, unless the rewrite is taking too long, then ill attempt to fix this

**Comment by vincentmetevelis** [comment]
Im optimizing the rendering of quests A LOT in the rewrite, so whenever i release it, this /*shouldn't*/ happen anymore
