### ISSUE TITLE
Crash on opening questbook

### ISSUE THREAD

**Issue by remplerus** [vincentmet/CustomQuests#26]
Hi,

I just installed CustomQuests to my modpack, but it keeps crashing if I just open the questbook.

Here's a crash log: [https://pastebin.com/D9qv7bZ3](https://pastebin.com/D9qv7bZ3)

It maybe has something to do with Woot FakePlayer, cause I had some other problems with another mod after I added Woot but its fixed as far as i know.

**Comment by Fungidelight** [comment]
I have had the same issue after modifying quests with dependencies, fixed it by deleting QuestingProgress.json and QuestingParties.json from the save file folder.

**Comment by vincentmetevelis** [comment]
It's the Blur mod

**Comment by remplerus** [comment]
jup, the blur mod was the problem. Just added "com.vincentmet.customquests.screens.ScreenQuestingDevice" to the guiExclusions in blur-client.toml.
