### ISSUE TITLE
Item quest rewards are voided if not enough space in the inventory

### ISSUE THREAD

**Issue by Fungidelight** [vincentmet/CustomQuests#27]
If player's inventory is full, when claiming the rewards, they are marked as claimed but the player does not receive the items.

**Comment by vincentmetevelis** [comment]
in survival it should drop on the ground. In creative the items get deleted

**Comment by Fungidelight** [comment]
Items do not drop on the ground in survival.

**Comment by vincentmetevelis** [comment]
Shouldn't happen, its working in the rewrite anyway :P Patience xD
