### ISSUE TITLE
[1.16.2] Move GUI

### ISSUE THREAD

**Issue by TheRealM18** [vincentmet/CustomQuests#31]
If your screen is too small, you are unable to claim, move around your quest, so you cant see them, and read the discription.

Expected.
Scales

Result.
does not scale well.

**Comment by vincentmetevelis** [comment]
As you can see/read on the CF page, the current version on CF doesn't cant do that yet, in the rewrite (not released yet) you will be able to. (last few images/GIFs on the CF page)
