### ISSUE TITLE
Crash when right clicking back button

### ISSUE THREAD

**Issue by AtelierAmber** [vincentmet/CustomQuests#32]
[crash-2020-09-25_14.25.06-client.txt](https://github.com/vincentmetevelis/CustomQuests/files/5285246/crash-2020-09-25_14.25.06-client.txt)

Attached crash log. Happens when right clicking the [Q] button at the top left of a quest.

**Comment by vincentmetevelis** [comment]
I cant reproduce it... When i rightclick on that button, i got back to the questline. Can you see if you can reproduce it, and if so, send the CF profile export so i can test it with you mods/configs?

**Comment by AtelierAmber** [comment]
Weird, I was able to reproduce it before but I restarted my computer this morning and now I can't. Sorry about that.

**Comment by vincentmetevelis** [comment]
alright, just reopen this issue, or create a new one  when it happens again 😉
